words = [
    "aabb",
    "aos",
    "biomejs",
    "cooldown",
    "cooldowns",
    "hitbox",
    "hitboxes",
    "lerp",
    "lifecycle",
    "longsword",
    "objectgroup",
    "pixelmix",
    "pointerdown",
    "pointermove",
    "pointerup",
    "proj",
    "snuggy",
    "soa",
    "spritesheet",
    "tilelayer",
    "tilemap",
    "tilemaps",
    "tileset",
    "tilesets",
    "vitest",
]
